version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $AWS_REPOSITORY .
      - docker tag $AWS_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPOSITORY:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPOSITORY:latest
      - echo Updating Lambda function with the new image...
      - aws lambda update-function-code --function-name your_lambda_function_name --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_REPOSITORY:latest

env:
  variables:
    AWS_REGION: "us-east-2"              # Replace with your AWS region
    AWS_ACCOUNT_ID: "314806948291"       # Replace with your AWS Account ID
    AWS_REPOSITORY: "lambda-repo"        # Replace with your ECR repository name
